spring.application.name=arbitrageengine

server.port=4040

spring.datasource.url=jdbc:postgresql://localhost:5432/arbitrage_db
spring.datasource.username=postgres
spring.datasource.password=admin123
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update